# Hello and welcome to the config.yml file!
# I tried to simplify this as much as possible!



console:
  enabled-msg: true # Will send a message in console if enabled.
  debug-mode: false # Currently not functional but will be soon!